// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ioebjmpteseatjsbyfxy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlvZWJqbXB0ZXNlYXRqc2J5Znh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2MTI2NDEsImV4cCI6MjA3MjE4ODY0MX0.sIXPShIEiPNBkTRyPUA1Fq5J88n7rIA7sTQVC4VOH4M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});